# Generated by Django 4.1.4 on 2022-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_message_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
